### ISSUE TITLE
Date and DateTime columns with missing values do not show up under 'datetime' category

### ISSUE THREAD

**Issue by George9000** [Hasnep/DataSkimmer.jl#55]
Both the numeric and categorical columns buckets or categories tolerate types that are unions with missing. For example, `Union{Missing, Int64}` shows up under the numeric column category. `Union{Missing, String}` is under the categorical columns category. However, `Union{Missing, Date}` and `Union{Missing, DateTime}` continue to be listed as 'categorical' columns.

**Comment by Hasnep** [comment]
Thanks for raising this issue @George9000, I've made a PR that will fix this and added some tests to catch this kind of thing in the future.
