### ISSUE TITLE
Columns with data entirely missing: put into Numeric and DateTime columns

### ISSUE THREAD

**Issue by George9000** [Hasnep/DataSkimmer.jl#59]
When a column has 100% of the rows missing, `skim` puts it in under _both_ the Numeric and DateTime lists. I think this is because both numeric and datetime column structs have Union with Missing as part of their definition while Categorical does not and is defined as `!is_numeric(x) && !is_datetime(x)` in helpers.jl

There may need to be a `is_missing(x)` function in helpers.jl for columns with all rows missing. Additionally, a new `struct` in DataSkimmer.jl called `AllMissingColumn`. This would be similar to the Categorical Column struct.

I opened one pull request (just figuring all this out) to correct one other error with Missing in datetime. I will try to work on this more extensive change if you don't get to it.

**Comment by George9000** [comment]
Added the AllMissingColumn struct. Made changes in both DataSkimmer.jl and helpers.jl.
Numeric or DateTime columns with some missing rows file to those categories. However, an occasional column with _all missing_ rows, now files only to the AllMissing category. Both commits are under one pull request.

**Comment by Hasnep** [comment]
Addresed in #58, will review and merge soon. Thanks @George9000!

**Comment by Hasnep** [comment]
This is a more detailed version of issue #46 so I'm closing that one.

**Comment by Hasnep** [comment]
This was fixed in PR #58 by @George9000. Thanks for your work!
