### ISSUE TITLE
Columns of Type Time incorrectly file under Categorical Columns

### ISSUE THREAD

**Issue by George9000** [Hasnep/DataSkimmer.jl#70]
Just caught this. A DataFrame with columns of Type Date and DateTime correctly file under the Datetime columns. However, a column of type **Time** files under categorical columns. See attached screenshot. Column names have been obscured on purpose.

![skimmer_bug](https://user-images.githubusercontent.com/16549651/159627393-afd55985-07e2-4965-8432-e222a6d66098.png)

**Comment by Hasnep** [comment]
Hi @George9000, thanks for spotting this. This issue should be fixed by #71, could you please check it works on your data and let me know if it solves your issue. To install the branch, you can run `add https://github.com/Hasnep/DataSkimmer.jl#fix/time-columns` from the Pkg REPL. Thanks again :)

**Comment by George9000** [comment]
Fix looks good!

![skim_updated](https://user-images.githubusercontent.com/16549651/160303589-d2d9fdcf-c692-410f-9d52-49729b3d2c0b.png)
