### ISSUE TITLE
Update version of dependency PrettyTables.jl

### ISSUE THREAD

**Issue by George9000** [Hasnep/DataSkimmer.jl#74]
PrettyTables has been [updated](https://discourse.julialang.org/t/ann-prettytables-jl-v2-0-0/86917?u=george9000) to version 2. The dependency in Project.toml `compat` for DataSkimmer should be updated to`PrettyTables = "1.0, 2"` which should then allow PrettyTable version `[1.0, 3.0.0)` as per [this documentation](https://pkgdocs.julialang.org/v1/compatibility/#Version-specifier-format).

**Comment by Hasnep** [comment]
Thanks @George9000, I’m away from a computer at the moment but will adjust the compat setting when I’m back :)

**Comment by Hasnep** [comment]
Fixed in #75, I'll be releasing a new version of DataSkimmer.jl soon, thanks again @George9000 :)
